# Boston Dataset

In [1]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [12]:
boston = load_boston()
boston["data"].shape

(506, 13)

In [15]:
boston["target"].shape

(506,)

In [16]:
boston["feature_names"]

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [17]:
type(boston)

sklearn.utils.Bunch

In [5]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [19]:
boston["target"].shape

(506,)

In [23]:
boston.target.size

506

In [25]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

In [26]:
y_data.shape

(506, 1)

In [30]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,5)).fit(x_data)
# standard_scale = preprocessing.StandardScaler().fit(x_data)

x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size = 0.33)

In [34]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

In [43]:
from sklearn import linear_model

regr = linear_model.LinearRegression(fit_intercept=True, normalize = False, copy_X = True, n_jobs=4)

regr.fit(X_train,y_train)
regr

LinearRegression(n_jobs=4)

In [44]:
regr.coef_, regr.intercept_

(array([[-2.11441781,  0.73029575,  0.32784275,  0.02403222, -1.82335804,
          4.07638664,  0.13230963, -2.94559738,  1.4745386 , -1.39177621,
         -2.01275833,  0.65494032, -3.77620621]]),
 array([26.79859242]))

In [45]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [46]:
y_true = y_test
y_hat = regr.predict(X_test)

r2_score(y_true, y_hat), mean_absolute_error(y_true,y_hat), mean_squared_error(y_true, y_hat)

(0.7508542238739127, 3.3826947136196863, 22.254339288610534)

In [48]:
y_true = y_data
y_hat = regr.predict(x_data)

r2_score(y_true, y_hat), mean_absolute_error(y_true,y_hat), mean_squared_error(y_true, y_hat)

(-2582.4708554988447, 374.3917785819029, 218095.46296360178)